'use client'

import { FileJson, LoaderCircle, Send } from 'lucide-react'
import { useState } from 'react'

type SubmitState =
  | { type: 'idle' }
  | { type: 'loading' }
  | { type: 'success'; id: string }
  | { type: 'error'; message: string }

export function SubmissionForm() {
  const [name, setName] = useState('')
  const [contact, setContact] = useState('')
  const [artifact, setArtifact] = useState('')
  const [state, setState] = useState<SubmitState>({ type: 'idle' })

  async function submit() {
    setState({ type: 'loading' })

    try {
      const parsed = JSON.parse(artifact)
      const response = await fetch('/api/submissions', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          artifact: parsed,
          submitterName: name || null,
          submitterContact: contact || null,
        }),
      })
      const body = (await response.json()) as { id?: string; error?: string }

      if (!response.ok) {
        throw new Error(body.error ?? 'Submission failed')
      }

      setState({ type: 'success', id: body.id ?? 'queued' })
    } catch (error) {
      setState({
        type: 'error',
        message:
          error instanceof Error
            ? error.message
            : 'Could not parse or submit project.json',
      })
    }
  }

  return (
    <div className="submit-panel">
      <div className="submit-head">
        <span className="submit-icon">
          <FileJson size={19} />
        </span>
        <div>
          <h1>Submit a Codex project</h1>
          <p>
            Paste the `project.json` generated by the Codex Showcase exporter.
            The app stores it as a private Supabase submission for review.
          </p>
        </div>
      </div>

      <div className="submit-grid">
        <label>
          <span>Name</span>
          <input
            value={name}
            onChange={(event) => setName(event.currentTarget.value)}
            placeholder="Ambassador or team"
          />
        </label>
        <label>
          <span>Contact</span>
          <input
            value={contact}
            onChange={(event) => setContact(event.currentTarget.value)}
            placeholder="Optional review contact"
          />
        </label>
      </div>

      <label className="artifact-input">
        <span>project.json</span>
        <textarea
          value={artifact}
          onChange={(event) => setArtifact(event.currentTarget.value)}
          placeholder='{"schemaVersion":"codex-showcase-project/v1","project":{...},"codexHistory":[...]}'
          rows={16}
        />
      </label>

      <div className="submit-actions">
        <button
          className="btn btn-primary"
          disabled={!artifact.trim() || state.type === 'loading'}
          onClick={submit}
          type="button"
        >
          {state.type === 'loading' ? (
            <LoaderCircle className="spin" size={16} />
          ) : (
            <Send size={16} />
          )}
          Submit for review
        </button>
        {state.type === 'success' && (
          <span className="submit-state ok">Queued as {state.id}</span>
        )}
        {state.type === 'error' && (
          <span className="submit-state error">{state.message}</span>
        )}
      </div>
    </div>
  )
}
